import asyncio
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select
from src.database import async_session, init_db
from src.models import CrawlQueue
from src.crawler import normalize_url, get_domain, is_ai_relevant


SEEDS = {
    "arxiv": [
        "https://arxiv.org/list/cs.AI/recent",
        "https://arxiv.org/list/cs.LG/recent",
        "https://arxiv.org/list/cs.CL/recent",
        "https://arxiv.org/list/cs.CV/recent",
        "https://arxiv.org/list/cs.RO/recent",
        "https://arxiv.org/list/cs.IR/recent",
        "https://arxiv.org/list/cs.DB/recent",
        "https://arxiv.org/list/cs.DC/recent",
        "https://arxiv.org/list/cs.GT/recent",
        "https://arxiv.org/list/cs.HC/recent",
        "https://arxiv.org/list/cs.MA/recent",
        "https://arxiv.org/list/cs.MM/recent",
        "https://arxiv.org/list/cs.NE/recent",
        "https://arxiv.org/list/cs.OS/recent",
        "https://arxiv.org/list/cs.PL/recent",
        "https://arxiv.org/list/cs.SC/recent",
        "https://arxiv.org/list/cs.SD/recent",
        "https://arxiv.org/list/cs.SE/recent",
        "https://arxiv.org/list/cs.SI/recent",
        "https://arxiv.org/list/cs.SY/recent",
        "https://arxiv.org/list/eess.IV/recent",
        "https://arxiv.org/list/eess.SP/recent",
        "https://arxiv.org/list/math.OC/recent",
        "https://arxiv.org/list/q-bio.NC/recent",
        "https://arxiv.org/list/stat.ML/recent",
        "https://arxiv.org/list/cs.AI/pastweek",
        "https://arxiv.org/list/cs.LG/pastweek",
        "https://arxiv.org/list/cs.CL/pastweek",
    ],
    "huggingface": [
        "https://huggingface.co/papers",
        "https://huggingface.co/blog",
        "https://huggingface.co/datasets",
        "https://huggingface.co/models",
        "https://huggingface.co/spaces",
        "https://huggingface.co/docs/transformers/index",
        "https://huggingface.co/docs/datasets/index",
        "https://huggingface.co/docs/tokenizers/index",
        "https://huggingface.co/docs/accelerate/index",
        "https://huggingface.co/docs/peft/index",
        "https://huggingface.co/docs/trl/index",
        "https://huggingface.co/blog?tag=research",
        "https://huggingface.co/blog?tag=open-source",
        "https://huggingface.co/blog?tag=guide",
        "https://huggingface.co/blog?tag=rl",
        "https://huggingface.co/blog?tag=diffusers",
        "https://huggingface.co/blog?tag=ethics",
        "https://huggingface.co/blog?tag=audio",
        "https://huggingface.co/blog?tag=vision",
    ],
    "openai": [
        "https://openai.com/research",
        "https://openai.com/blog",
        "https://platform.openai.com/docs",
        "https://openai.com/research/index",
        "https://openai.com/research?topics=alignment",
        "https://openai.com/research?topics=gpt-4",
        "https://openai.com/research?topics=safety",
        "https://openai.com/research?topics=multimodal",
        "https://openai.com/research?topics=robotics",
    ],
    "anthropic": [
        "https://www.anthropic.com/research",
        "https://www.anthropic.com/news",
        "https://www.anthropic.com/research/alignment",
        "https://www.anthropic.com/research/safety",
        "https://docs.anthropic.com/en/docs/",
        "https://www.anthropic.com/research/claude",
        "https://www.anthropic.com/research/long-context",
    ],
    "google_deepmind": [
        "https://deepmind.google/research/",
        "https://deepmind.google/discover/blog/",
        "https://deepmind.google/research/highlighted-research/",
        "https://deepmind.google/research/publications/",
        "https://deepmind.google/discover/?category=research",
        "https://deepmind.google/discover/?category=responsibility",
        "https://blog.google/technology/ai/",
        "https://blog.research.google/",
        "https://ai.google/discover/",
        "https://ai.google/research/",
        "https://ai.googleblog.com/",
        "https://research.google/pubs/",
        "https://research.google/teams/",
        "https://research.google/tools/",
    ],
    "meta_ai": [
        "https://ai.meta.com/research/",
        "https://ai.meta.com/blog/",
        "https://ai.meta.com/research/publications/",
        "https://ai.meta.com/research/llama/",
        "https://ai.meta.com/datasets/",
        "https://engineering.fb.com/category/ai-research/",
    ],
    "microsoft": [
        "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/",
        "https://www.microsoft.com/en-us/research/research-area/machine-learning/",
        "https://www.microsoft.com/en-us/research/research-area/natural-language-processing/",
        "https://www.microsoft.com/en-us/research/research-area/computer-vision/",
        "https://www.microsoft.com/en-us/research/blog/",
        "https://azure.microsoft.com/en-us/blog/topics/ai/",
        "https://github.com/microsoft/DeepSpeed",
        "https://github.com/microsoft/FLAML",
        "https://github.com/microsoft/presidio",
    ],
    "nvidia": [
        "https://www.nvidia.com/en-us/research/",
        "https://developer.nvidia.com/blog/",
        "https://developer.nvidia.com/blog/category/ai-data-science/",
        "https://developer.nvidia.com/blog/category/deep-learning/",
        "https://developer.nvidia.com/blog/category/generative-ai/",
        "https://developer.nvidia.com/blog/category/natural-language-processing/",
        "https://blogs.nvidia.com/blog/category/research/",
        "https://github.com/NVIDIA/Megatron-LM",
        "https://github.com/NVIDIA/NeMo",
        "https://github.com/NVIDIA/TensorRT-LLM",
    ],
    "stanford": [
        "https://ai.stanford.edu/blog/",
        "https://crfm.stanford.edu/",
        "https://hai.stanford.edu/news",
        "https://nlp.stanford.edu/",
        "https://cs.stanford.edu/research/ai",
        "https://web.stanford.edu/class/cs224n/",
        "https://web.stanford.edu/class/cs231n/",
        "https://web.stanford.edu/class/cs229/",
        "https://web.stanford.edu/class/cs234/",
    ],
    "berkeley": [
        "https://bair.berkeley.edu/blog/",
        "https://rise.cs.berkeley.edu/",
        "https://sky.cs.berkeley.edu/",
        "https://eecs.berkeley.edu/research/area/artificial-intelligence",
    ],
    "mit": [
        "https://www.csail.mit.edu/research/artificial-intelligence",
        "https://www.csail.mit.edu/research/machine-learning",
        "https://news.mit.edu/topic/artificial-intelligence2",
        "https://news.mit.edu/topic/computers-and-technology",
        "https://cbmm.mit.edu/research",
        "https://www.mit.edu/~amini/pubs/",
    ],
    "other_labs": [
        "https://www.adept.ai/blog",
        "https://cohere.com/blog",
        "https://mistral.ai/news/",
        "https://www.together.ai/blog",
        "https://www.perplexity.ai/hub/blog",
        "https://stability.ai/news",
        "https://runwayml.com/blog/",
        "https://eleuther.ai/publications/",
        "https://blog.eleuther.ai/",
        "https://www.mosaicml.com/blog",
        "https://www.databricks.com/blog/ai",
        "https://www.databricks.com/blog/machine-learning",
        "https://blog.research.google/search/label/Natural%20Language%20Processing",
        "https://blog.research.google/search/label/Machine%20Learning",
        "https://blog.research.google/search/label/Computer%20Vision",
    ],
    "papers_benchmarks": [
        "https://paperswithcode.com/",
        "https://paperswithcode.com/sota",
        "https://paperswithcode.com/methods",
        "https://paperswithcode.com/datasets",
        "https://paperswithcode.com/area/natural-language-processing",
        "https://paperswithcode.com/area/computer-vision",
        "https://paperswithcode.com/area/reinforcement-learning",
        "https://paperswithcode.com/area/speech",
        "https://paperswithcode.com/area/medical",
        "https://openreview.net/group?id=NeurIPS.cc",
        "https://openreview.net/group?id=ICML.cc",
        "https://openreview.net/group?id=ICLR.cc",
        "https://iclr.cc/",
        "https://icml.cc/",
        "https://neurips.cc/",
        "https://nips.cc/",
        "https://aaai.org/",
        "https://www.ijcai.org/",
        "https://aclweb.org/aclwiki/Main_Page",
        "https://www.aclweb.org/anthology/",
        "https://www.visionmeetscognition.org/",
        "https://lmsys.org/",
        "https://lmarena.ai/",
        "https://lmsys.org/blog/",
        "https://chat.lmsys.org/",
        "https://huggingface.co/spaces/lmsys/chatbot-arena-leaderboard",
        "https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard",
        "https://crfm.stanford.edu/helm/",
        "https://crfm.stanford.edu/helm/lite/latest/",
        "https://crfm.stanford.edu/ecosystem-graphs/",
        "https://www.benchmarks.ai/",
        "https://www.benchmarks.ai/leaderboard",
        "https://big-bench.github.io/",
        "https://github.com/google/BIG-bench",
        "https://github.com/EleutherAI/lm-evaluation-harness",
        "https://github.com/openai/evals",
    ],
    "distill_lesswrong": [
        "https://distill.pub/",
        "https://distill.pub/2017/feature-visualization/",
        "https://distill.pub/2020/attribution-baselines/",
        "https://distill.pub/2021/multimodal-neurons/",
        "https://www.lesswrong.com/",
        "https://www.lesswrong.com/posts",
        "https://www.lesswrong.com/library",
        "https://alignmentforum.org/",
        "https://alignmentforum.org/library",
        "https://www.alignmentforum.org/allPosts",
    ],
    "dev_frameworks": [
        "https://pytorch.org/blog/",
        "https://pytorch.org/tutorials/",
        "https://blog.tensorflow.org/",
        "https://www.tensorflow.org/tutorials",
        "https://www.tensorflow.org/guide",
        "https://jax.readthedocs.io/en/latest/",
        "https://flax.readthedocs.io/en/latest/",
        "https://optax.readthedocs.io/en/latest/",
        "https://huggingface.co/docs/transformers/index",
        "https://huggingface.co/docs/diffusers/index",
        "https://huggingface.co/docs/accelerate/index",
        "https://huggingface.co/docs/peft/index",
        "https://huggingface.co/docs/trl/index",
        "https://docs.ray.io/en/latest/",
        "https://www.ray.io/blog",
        "https://vllm.ai/",
        "https://docs.vllm.ai/en/latest/",
        "https://sglang.ai/",
        "https://docs.llamaindex.ai/",
        "https://python.langchain.com/docs/",
        "https://www.llamaindex.ai/blog",
        "https://blog.langchain.dev/",
        "https://docs.crewai.com/",
        "https://weaviate.io/blog",
        "https://www.pinecone.io/blog/",
        "https://www.trychroma.com/",
        "https://qdrant.tech/blog/",
        "https://www.milvus.io/blog",
    ],
    "wandb_mlops": [
        "https://wandb.ai/fully-connected",
        "https://wandb.ai/site/articles",
        "https://docs.wandb.ai/",
        "https://neptune.ai/blog",
        "https://neptune.ai/resources",
        "https://dagshub.com/blog",
        "https://comet.com/site/resources/blog/",
        "https://www.comet.com/site/blog/",
        "https://neptune.ai/blog",
        "https://www.mlflow.org/docs/latest/index.html",
    ],
    "github_repos": [
        "https://github.com/huggingface/transformers",
        "https://github.com/huggingface/diffusers",
        "https://github.com/huggingface/datasets",
        "https://github.com/huggingface/tokenizers",
        "https://github.com/huggingface/peft",
        "https://github.com/huggingface/trl",
        "https://github.com/huggingface/accelerate",
        "https://github.com/huggingface/text-generation-inference",
        "https://github.com/openai/whisper",
        "https://github.com/openai/gpt-2",
        "https://github.com/openai/openai-python",
        "https://github.com/openai/evals",
        "https://github.com/anthropics/anthropic-cookbook",
        "https://github.com/anthropics/anthropic-sdk-python",
        "https://github.com/anthropics/claude-code",
        "https://github.com/pytorch/pytorch",
        "https://github.com/pytorch/vision",
        "https://github.com/pytorch/audio",
        "https://github.com/pytorch/fairseq",
        "https://github.com/tensorflow/tensorflow",
        "https://github.com/google/jax",
        "https://github.com/google-research/google-research",
        "https://github.com/google-research/bert",
        "https://github.com/google-research/t5x",
        "https://github.com/EleutherAI/gpt-neox",
        "https://github.com/EleutherAI/lm-evaluation-harness",
        "https://github.com/EleutherAI/pythia",
        "https://github.com/EleutherAI/dps",
        "https://github.com/Lightning-AI/lightning",
        "https://github.com/Lightning-AI/litgpt",
        "https://github.com/Lightning-AI/lit-llama",
        "https://github.com/microsoft/DeepSpeed",
        "https://github.com/microsoft/FLAML",
        "https://github.com/NVIDIA/Megatron-LM",
        "https://github.com/NVIDIA/NeMo",
        "https://github.com/NVIDIA/TensorRT-LLM",
        "https://github.com/NVIDIA/apex",
        "https://github.com/vllm-project/vllm",
        "https://github.com/sgl-project/sglang",
        "https://github.com/run-llama/llama_index",
        "https://github.com/langchain-ai/langchain",
        "https://github.com/langchain-ai/langgraph",
        "https://github.com/crewAIInc/crewAI",
        "https://github.com/QwenLM/Qwen",
        "https://github.com/QwenLM/Qwen2",
        "https://github.com/meta-llama/llama",
        "https://github.com/meta-llama/llama-recipes",
        "https://github.com/mistralai/mistral-inference",
        "https://github.com/mistralai/cookbook",
        "https://github.com/cohere-ai/cohere-python",
        "https://github.com/cohere-ai/cohere-toolkit",
        "https://github.com/ Stability-AI/stablediffusion",
        "https://github.com/ Stability-AI/generative-models",
        "https://github.com/Stability-AI/stablediffusion",
        "https://github.com/Stability-AI/generative-models",
        "https://github.com/open-mmlab/mmdetection",
        "https://github.com/open-mmlab/mmsegmentation",
        "https://github.com/open-mmlab/mmpose",
        "https://github.com/facebookresearch/fairseq",
        "https://github.com/facebookresearch/llama",
        "https://github.com/facebookresearch/detectron2",
        "https://github.com/facebookresearch/segment-anything",
        "https://github.com/facebookresearch/dinov2",
        "https://github.com/facebookresearch/ImageBind",
        "https://github.com/FlagOpen/FlagEmbedding",
        "https://github.com/FlagOpen/FlagAI",
        "https://github.com/baaivision/EVA",
        "https://github.com/baaivision/Emu",
        "https://github.com/mlfoundations/open_clip",
        "https://github.com/mlfoundations/open_lm",
        "https://github.com/mlfoundations/datacomp",
    ],
    "newsletters_news": [
        "https://www.deeplearning.ai/the-batch/",
        "https://www.deeplearning.ai/short-courses/",
        "https://importai.substack.com/",
        "https://thesequence.substack.com/",
        "https://www.tldrnewsletter.com/ai",
        "https://www.tldrnewsletter.com/machine-learning",
        "https://www.notion.so/blog/topic/ai",
        "https://blog.nvidia.com/",
        "https://techcrunch.com/category/artificial-intelligence/",
        "https://venturebeat.com/ai/",
        "https://www.wired.com/tag/artificial-intelligence/",
        "https://www.technologyreview.com/topic/artificial-intelligence/",
        "https://spectrum.ieee.org/topic/artificial-intelligence/",
        "https://ai-journal.com/",
        "https://artificialintelligence-news.com/",
        "https://www.analyticsvidhya.com/blog/",
        "https://towardsdatascience.com/",
        "https://medium.com/tag/artificial-intelligence",
        "https://medium.com/tag/machine-learning",
        "https://medium.com/tag/deep-learning",
        "https://medium.com/tag/large-language-models",
        "https://dev.to/t/ai",
        "https://dev.to/t/machinelearning",
        "https://www.kdnuggets.com/",
        "https://www.marktechpost.com/",
        "https://www.unite.ai/",
    ],
    "kaggle_reddit": [
        "https://www.kaggle.com/datasets?tags=13204-Computer+Science",
        "https://www.kaggle.com/datasets?tags=13207-Natural+Language+Processing",
        "https://www.kaggle.com/datasets?tags=13208-Computer+Vision",
        "https://www.kaggle.com/competitions",
        "https://www.kaggle.com/discussions",
        "https://www.reddit.com/r/MachineLearning/",
        "https://www.reddit.com/r/LocalLLaMA/",
        "https://www.reddit.com/r/artificial/",
        "https://www.reddit.com/r/deeplearning/",
        "https://www.reddit.com/r/LanguageTechnology/",
    ],
    "misc_ai": [
        "https://www.gemini.com/",
        "https://gemini.google.com/",
        "https://aistudio.google.com/app/apps/drive/",
        "https://ai.google.dev/",
        "https://ai.google.dev/gemini-api/docs",
        "https://ai.google.dev/edge/mediapipe/solutions/guide",
        "https://www.anthropic.com/research/claude",
        "https://www.anthropic.com/research/long-context",
        "https://claude.ai/",
        "https://chat.openai.com/",
        "https://platform.openai.com/docs/guides",
        "https://platform.openai.com/docs/api-reference",
        "https://cookbook.openai.com/",
        "https://github.com/openai/openai-cookbook",
        "https://github.com/anthropics/anthropic-cookbook",
        "https://huggingface.co/learn",
        "https://huggingface.co/learn/nlp-course",
        "https://huggingface.co/learn/deep-rl-course",
        "https://huggingface.co/learn/audio-course",
        "https://huggingface.co/learn/computer-vision-course",
        "https://huggingface.co/learn/llm-course",
        "https://huggingface.co/learn/agentic-llm-course",
    ],
}


def get_all_urls():
    urls = []
    for category, items in SEEDS.items():
        for url in items:
            norm = normalize_url(url)
            if is_ai_relevant(norm):
                urls.append((norm, get_domain(norm), category))
    return urls


async def main():
    await init_db()
    all_urls = get_all_urls()
    count = 0
    async with async_session() as session:
        for url, domain, category in all_urls:
            existing = await session.execute(select(CrawlQueue).where(CrawlQueue.url == url))
            if existing.scalar_one_or_none():
                continue
            # Assign priority based on category
            priority_map = {
                "arxiv": 200, "papers_benchmarks": 190, "huggingface": 180,
                "openai": 170, "anthropic": 170, "google_deepmind": 160,
                "distill_lesswrong": 150, "stanford": 140, "berkeley": 140,
                "mit": 140, "dev_frameworks": 130, "github_repos": 120,
                "nvidia": 130, "meta_ai": 130, "microsoft": 130,
                "other_labs": 120, "wandb_mlops": 100,
                "newsletters_news": 80, "kaggle_reddit": 70, "misc_ai": 60,
            }
            priority = priority_map.get(category, 50)
            session.add(CrawlQueue(url=url, priority=priority, domain=domain))
            count += 1
        await session.commit()
    print(f"Seeded {count} URLs across {len(SEEDS)} categories")


if __name__ == "__main__":
    asyncio.run(main())
